name: Integration Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: ${{ hashFiles('go.sum') }}
      - name: Setup Kind CLI
        run: |
          sudo curl -sSLo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.10.0/kind-linux-amd64
          sudo chmod +x /usr/local/bin/kind
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        id: install
      - name: Setup Ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
      - name: Setup Flux v2 CLI
        uses: fluxcd/flux2/action@main
      - name: Test
        env:
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          PATH=$PATH:$(go env GOPATH)/bin make integration
